Repository freenode/ircd-seven, pull requests merged in 2018-02, with the labels that each got.

#122 sasl_usercloak: check K-lines after host change
  extensions/sasl_usercloak.c
Labels: bug, needs review, on testnet

#113 Update hint strings where possible
  extensions/hints.c
Labels: needs testing

#114 Update numeric 435 to reflect +q stopping /nick
  src/messages.tab
Labels: needs testing

#31 add @ prefix to op-moderated (+z) messages
  doc/example.conf
  doc/reference.conf
  include/s_conf.h
  modules/m_info.c
  src/newconf.c
  src/s_conf.c
  src/send.c
Labels: enhancement, needs testing, on testnet
