Repository freenode/ircd-seven, pull requests merged in 2019-03, with the labels that each got.

#155 assorted spelling fixes
  modules/core/m_message.c
  modules/m_info.c
  modules/m_stats.c
  src/channel.c
  src/s_user.c
Labels: enhancement

#152 m_resv: Fix number of minutes in snote
  modules/m_resv.c
Labels: enhancement

#151 m_ison: Do not report unregistered connections
  modules/m_ison.c
Labels: bug

#141 Don't ratelimit /stats with no server argument
  modules/m_stats.c
Labels: enhancement, on testnet

#144 Extend +M kick protection to IsAnyOper
  modules/core/m_kick.c
Labels: enhancement, on testnet

#145 remove extensions/override.c
  doc/reference.conf
  extensions/Makefile.in
  extensions/override.c
Labels: on testnet

#146 Remove general.kline_delay config option
  doc/reference.conf
  include/s_conf.h
  modules/m_info.c
  src/newconf.c
  src/s_conf.c
Labels: on testnet

#148 Don't ratelimit local /motd
  modules/m_motd.c
Labels: enhancement

#158 Don't build m_filter when there is no hyperscan
  configure.ac
  extensions/Makefile.in
Labels: bug
